/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kniffel.gui;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import kniffel.logiikka.Pelialusta;

/**
 *
 * @author niklasad
 */
public class PeliIkkuna extends javax.swing.JFrame {

    /**
     * Creates new form Kayttoliittyma
     */
    private Pelialusta pelialusta;
    private List<JButton> nopat;
    
    
    public PeliIkkuna(Pelialusta alusta) {
        this.pelialusta  =  alusta;
        this.nopat = new ArrayList<>();
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tulokset = new javax.swing.JPanel();
        ykkosetButton = new javax.swing.JButton();
        kakkosetButton = new javax.swing.JButton();
        kolmosetButton = new javax.swing.JButton();
        nelosetButton = new javax.swing.JButton();
        viitosetButton = new javax.swing.JButton();
        kutosetButton = new javax.swing.JButton();
        pariButton = new javax.swing.JButton();
        kaksiPariaButton = new javax.swing.JButton();
        suoraButton = new javax.swing.JButton();
        isoSuoraButton = new javax.swing.JButton();
        kolmesamaaButton = new javax.swing.JButton();
        neljasamaaButton = new javax.swing.JButton();
        takariButton = new javax.swing.JButton();
        sattumaButton = new javax.swing.JButton();
        yatsiButton = new javax.swing.JButton();
        valisummaLabel = new javax.swing.JLabel();
        hyvitysLabel = new javax.swing.JLabel();
        summaLabel = new javax.swing.JLabel();
        pelaajaLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tulosTaulu = new javax.swing.JTable();
        Nopat = new javax.swing.JPanel();
        noppa1Button = new javax.swing.JButton();
        noppa2Button = new javax.swing.JButton();
        noppa3Button = new javax.swing.JButton();
        noppa4Button = new javax.swing.JButton();
        noppa5Button = new javax.swing.JButton();
        heittoButton = new javax.swing.JButton();
        statusLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kniffel");

        Tulokset.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ykkosetButton.setText("Ykköset");
        ykkosetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ykkosetButtonMouseClicked(evt);
            }
        });
        ykkosetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ykkosetButtonActionPerformed(evt);
            }
        });

        kakkosetButton.setText("Kakkoset");

        kolmosetButton.setText("Kolmoset");

        nelosetButton.setText("Neloset");

        viitosetButton.setText("Viitoset");

        kutosetButton.setText("Kutoset");

        pariButton.setText("Pari");

        kaksiPariaButton.setText("Kaksi paria");

        suoraButton.setText("Pieni suora");

        isoSuoraButton.setText("Suuri suora");

        kolmesamaaButton.setText("Kolme samaa");

        neljasamaaButton.setText("Neljä samaa");

        takariButton.setText("Täyskäsi");

        sattumaButton.setText("Sattuma");

        yatsiButton.setText("Kniffel");

        valisummaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valisummaLabel.setText("Välisumma");
        valisummaLabel.setAlignmentX(5.0F);
        valisummaLabel.setAlignmentY(0.1F);
        valisummaLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        hyvitysLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hyvitysLabel.setText("Hyvitys");
        hyvitysLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        summaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        summaLabel.setText("Summa");
        summaLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        summaLabel.setPreferredSize(new java.awt.Dimension(64, 19));

        pelaajaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pelaajaLabel.setText("Pelaaja");
        pelaajaLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tulosTaulu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tulosTaulu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Pelaaja 1", "Pelaaja 2", "Pelaaja 3", "Pelaaja 4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tulosTaulu.setRowHeight(36);
        tulosTaulu.setRowSelectionAllowed(false);
        jScrollPane2.setViewportView(tulosTaulu);

        javax.swing.GroupLayout TuloksetLayout = new javax.swing.GroupLayout(Tulokset);
        Tulokset.setLayout(TuloksetLayout);
        TuloksetLayout.setHorizontalGroup(
            TuloksetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TuloksetLayout.createSequentialGroup()
                .addGroup(TuloksetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(summaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hyvitysLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(TuloksetLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(TuloksetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(valisummaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pariButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(TuloksetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(ykkosetButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(kakkosetButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(kolmosetButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nelosetButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(TuloksetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(viitosetButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(kutosetButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(pelaajaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(kaksiPariaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(suoraButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(isoSuoraButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kolmesamaaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(neljasamaaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(takariButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sattumaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(yatsiButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(476, 476, 476))
        );

        TuloksetLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {isoSuoraButton, kakkosetButton, kaksiPariaButton, kolmesamaaButton, kolmosetButton, kutosetButton, neljasamaaButton, nelosetButton, pariButton, sattumaButton, suoraButton, takariButton, viitosetButton, yatsiButton, ykkosetButton});

        TuloksetLayout.setVerticalGroup(
            TuloksetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TuloksetLayout.createSequentialGroup()
                .addGroup(TuloksetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, TuloksetLayout.createSequentialGroup()
                        .addComponent(pelaajaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ykkosetButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kakkosetButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kolmosetButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nelosetButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viitosetButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kutosetButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valisummaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hyvitysLabel)
                        .addGap(8, 8, 8)
                        .addComponent(pariButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kaksiPariaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(suoraButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(isoSuoraButton)
                        .addGap(11, 11, 11)
                        .addComponent(kolmesamaaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(neljasamaaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(takariButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sattumaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yatsiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(summaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        TuloksetLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {hyvitysLabel, isoSuoraButton, kakkosetButton, kaksiPariaButton, kolmesamaaButton, kolmosetButton, kutosetButton, neljasamaaButton, nelosetButton, pariButton, sattumaButton, suoraButton, takariButton, valisummaLabel, viitosetButton, ykkosetButton});

        Nopat.setBackground(java.awt.Color.white);
        Nopat.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        noppa1Button.setText("Noppa1");
        noppa1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noppa1ButtonActionPerformed(evt);
            }
        });
        this.nopat.add(noppa1Button);

        noppa2Button.setText("Noppa2");
        noppa2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noppa2ButtonActionPerformed(evt);
            }
        });
        this.nopat.add(noppa2Button);

        noppa3Button.setText("Noppa3");
        noppa3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noppa3ButtonActionPerformed(evt);
            }
        });
        this.nopat.add(noppa3Button);

        noppa4Button.setText("Noppa4");
        noppa4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noppa4ButtonActionPerformed(evt);
            }
        });
        this.nopat.add(noppa4Button);

        noppa5Button.setText("Noppa5");
        noppa5Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noppa5ButtonActionPerformed(evt);
            }
        });
        this.nopat.add(noppa5Button);

        heittoButton.setText("Heitä nopat!");
        this.heittoButton.addActionListener(new HeitonKuuntelija(this.pelialusta, this.nopat, heittoButton, statusLabel));

        javax.swing.GroupLayout NopatLayout = new javax.swing.GroupLayout(Nopat);
        Nopat.setLayout(NopatLayout);
        NopatLayout.setHorizontalGroup(
            NopatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NopatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NopatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(heittoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(noppa5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noppa4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noppa3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noppa2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noppa1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        NopatLayout.setVerticalGroup(
            NopatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NopatLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(noppa1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noppa2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noppa3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noppa4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noppa5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(heittoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        statusLabel.setText("           Status");
        statusLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Tulokset, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Nopat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(statusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Nopat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addComponent(Tulokset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ykkosetButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ykkosetButtonMouseClicked
        this.tulosTaulu.setValueAt((Integer) 3, 0, 0);// TODO add your handling code here:
    }//GEN-LAST:event_ykkosetButtonMouseClicked

    private void noppa1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noppa1ButtonActionPerformed
        this.pelialusta.getNopat().get(0).saasta();// TODO add your handling code here:
    }//GEN-LAST:event_noppa1ButtonActionPerformed

    private void noppa2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noppa2ButtonActionPerformed
        this.pelialusta.getNopat().get(1).saasta();
    }//GEN-LAST:event_noppa2ButtonActionPerformed

    private void noppa3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noppa3ButtonActionPerformed
        this.pelialusta.getNopat().get(2).saasta();        
    }//GEN-LAST:event_noppa3ButtonActionPerformed

    private void noppa4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noppa4ButtonActionPerformed
        this.pelialusta.getNopat().get(3).saasta();        // TODO add your handling code here:
    }//GEN-LAST:event_noppa4ButtonActionPerformed

    private void noppa5ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noppa5ButtonActionPerformed
        this.pelialusta.getNopat().get(4).saasta();        // TODO add your handling code here:
    }//GEN-LAST:event_noppa5ButtonActionPerformed

    private void ykkosetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ykkosetButtonActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_ykkosetButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(KayttoliittymaIkkuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(KayttoliittymaIkkuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(KayttoliittymaIkkuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(KayttoliittymaIkkuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PeliIkkuna().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Nopat;
    private javax.swing.JPanel Tulokset;
    private javax.swing.JButton heittoButton;
    private javax.swing.JLabel hyvitysLabel;
    private javax.swing.JButton isoSuoraButton;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton kakkosetButton;
    private javax.swing.JButton kaksiPariaButton;
    private javax.swing.JButton kolmesamaaButton;
    private javax.swing.JButton kolmosetButton;
    private javax.swing.JButton kutosetButton;
    private javax.swing.JButton neljasamaaButton;
    private javax.swing.JButton nelosetButton;
    private javax.swing.JButton noppa1Button;
    private javax.swing.JButton noppa2Button;
    private javax.swing.JButton noppa3Button;
    private javax.swing.JButton noppa4Button;
    private javax.swing.JButton noppa5Button;
    private javax.swing.JButton pariButton;
    private javax.swing.JLabel pelaajaLabel;
    private javax.swing.JButton sattumaButton;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel summaLabel;
    private javax.swing.JButton suoraButton;
    private javax.swing.JButton takariButton;
    private javax.swing.JTable tulosTaulu;
    private javax.swing.JLabel valisummaLabel;
    private javax.swing.JButton viitosetButton;
    private javax.swing.JButton yatsiButton;
    private javax.swing.JButton ykkosetButton;
    // End of variables declaration//GEN-END:variables
}
