/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kniffel.gui;

import kniffel.logiikka.Pelialusta;

/**
 *
 * @author niklasad
 */
public class PeliIkkuna extends javax.swing.JFrame {

    /**
     * Creates new form Kayttoliittyma
     */
    private Pelialusta pelialusta;
    
    public PeliIkkuna() {
        this.pelialusta  =  new Pelialusta();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Tulokset = new javax.swing.JPanel();
        ykkosetButton = new javax.swing.JButton();
        kakkosetButton = new javax.swing.JButton();
        kolmosetButton = new javax.swing.JButton();
        nelosetButton = new javax.swing.JButton();
        viitosetButton = new javax.swing.JButton();
        kutosetButton = new javax.swing.JButton();
        pariButton = new javax.swing.JButton();
        kaksiPariaButton = new javax.swing.JButton();
        suoraButton = new javax.swing.JButton();
        isoSuoraButton = new javax.swing.JButton();
        kolmesamaaButton = new javax.swing.JButton();
        neljasamaaButton = new javax.swing.JButton();
        takariButton = new javax.swing.JButton();
        sattumaButton = new javax.swing.JButton();
        yatsiButton = new javax.swing.JButton();
        valisummaLabel = new javax.swing.JLabel();
        hyvitysLabel = new javax.swing.JLabel();
        summaLabel = new javax.swing.JLabel();
        pelaajaLabel = new javax.swing.JLabel();
        Nopat = new javax.swing.JPanel();
        noppa1Button = new javax.swing.JButton();
        noppa2Button = new javax.swing.JButton();
        noppa3Button = new javax.swing.JButton();
        noppa4Button = new javax.swing.JButton();
        noppa5Button = new javax.swing.JButton();
        heittoButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        statusLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kniffel");

        Tulokset.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ykkosetButton.setText("Ykköset");
        ykkosetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ykkosetButtonMouseClicked(evt);
            }
        });

        kakkosetButton.setText("Kakkoset");

        kolmosetButton.setText("Kolmoset");

        nelosetButton.setText("Neloset");

        viitosetButton.setText("Viitoset");

        kutosetButton.setText("Kutoset");

        pariButton.setText("Pari");

        kaksiPariaButton.setText("Kaksi paria");

        suoraButton.setText("Pieni suora");

        isoSuoraButton.setText("Suuri suora");

        kolmesamaaButton.setText("Kolme samaa");

        neljasamaaButton.setText("Neljä samaa");

        takariButton.setText("Täyskäsi");

        sattumaButton.setText("Sattuma");

        yatsiButton.setText("Kniffel");

        valisummaLabel.setText("     Välisumma");
        valisummaLabel.setAlignmentX(5.0F);
        valisummaLabel.setAlignmentY(0.1F);
        valisummaLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        hyvitysLabel.setText("       Hyvitys");
        hyvitysLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        summaLabel.setText("      Summa");
        summaLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        summaLabel.setPreferredSize(new java.awt.Dimension(64, 19));

        pelaajaLabel.setText("       Pelaaja");
        pelaajaLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout TuloksetLayout = new javax.swing.GroupLayout(Tulokset);
        Tulokset.setLayout(TuloksetLayout);
        TuloksetLayout.setHorizontalGroup(
            TuloksetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pelaajaLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TuloksetLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(TuloksetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(valisummaLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(summaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hyvitysLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kakkosetButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(yatsiButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ykkosetButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kolmosetButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nelosetButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viitosetButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kutosetButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pariButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kaksiPariaButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(suoraButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(isoSuoraButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kolmesamaaButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(neljasamaaButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(takariButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sattumaButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        TuloksetLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {isoSuoraButton, kakkosetButton, kaksiPariaButton, kolmesamaaButton, kolmosetButton, kutosetButton, neljasamaaButton, nelosetButton, pariButton, sattumaButton, suoraButton, takariButton, viitosetButton, yatsiButton, ykkosetButton});

        TuloksetLayout.setVerticalGroup(
            TuloksetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TuloksetLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(pelaajaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ykkosetButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kakkosetButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kolmosetButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nelosetButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viitosetButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kutosetButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valisummaLabel)
                .addGap(2, 2, 2)
                .addComponent(hyvitysLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pariButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kaksiPariaButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(suoraButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(isoSuoraButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kolmesamaaButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(neljasamaaButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(takariButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sattumaButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yatsiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(summaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
        );

        TuloksetLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {hyvitysLabel, isoSuoraButton, kakkosetButton, kaksiPariaButton, kolmesamaaButton, kolmosetButton, kutosetButton, neljasamaaButton, nelosetButton, pariButton, sattumaButton, suoraButton, takariButton, valisummaLabel, viitosetButton, ykkosetButton});

        Nopat.setBackground(java.awt.Color.white);
        Nopat.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        noppa1Button.setText("Noppa1");
        noppa1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noppa1ButtonActionPerformed(evt);
            }
        });

        noppa2Button.setText("Noppa2");
        noppa2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noppa2ButtonActionPerformed(evt);
            }
        });

        noppa3Button.setText("Noppa3");
        noppa3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noppa3ButtonActionPerformed(evt);
            }
        });

        noppa4Button.setText("Noppa4");
        noppa4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noppa4ButtonActionPerformed(evt);
            }
        });

        noppa5Button.setText("Noppa5");
        noppa5Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noppa5ButtonActionPerformed(evt);
            }
        });

        heittoButton.setText("Heitä nopat!");
        heittoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heittoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NopatLayout = new javax.swing.GroupLayout(Nopat);
        Nopat.setLayout(NopatLayout);
        NopatLayout.setHorizontalGroup(
            NopatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NopatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NopatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, NopatLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(NopatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noppa1Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noppa2Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noppa3Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noppa4Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noppa5Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(heittoButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        NopatLayout.setVerticalGroup(
            NopatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NopatLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(noppa1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noppa2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noppa3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noppa4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noppa5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(heittoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(37);
        jScrollPane1.setViewportView(jTable1);

        statusLabel.setText("           Status");
        statusLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Tulokset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Nopat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(statusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Nopat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35))))
                    .addComponent(Tulokset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ykkosetButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ykkosetButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ykkosetButtonMouseClicked

    private void noppa1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noppa1ButtonActionPerformed
        this.pelialusta.getNopat().get(0).saasta();// TODO add your handling code here:
    }//GEN-LAST:event_noppa1ButtonActionPerformed

    private void heittoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heittoButtonActionPerformed
        this.pelialusta.heitaNopat();
        noppa1Button.setLabel(pelialusta.getNopat().get(0).toString());
        noppa2Button.setLabel(pelialusta.getNopat().get(1).toString());
        noppa3Button.setLabel(pelialusta.getNopat().get(2).toString());
        noppa4Button.setLabel(pelialusta.getNopat().get(3).toString());
        noppa5Button.setLabel(pelialusta.getNopat().get(4).toString());
    }//GEN-LAST:event_heittoButtonActionPerformed

    private void noppa2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noppa2ButtonActionPerformed
        this.pelialusta.getNopat().get(1).saasta();
    }//GEN-LAST:event_noppa2ButtonActionPerformed

    private void noppa3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noppa3ButtonActionPerformed
        this.pelialusta.getNopat().get(2).saasta();        // TODO add your handling code here:
    }//GEN-LAST:event_noppa3ButtonActionPerformed

    private void noppa4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noppa4ButtonActionPerformed
        this.pelialusta.getNopat().get(3).saasta();        // TODO add your handling code here:
    }//GEN-LAST:event_noppa4ButtonActionPerformed

    private void noppa5ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noppa5ButtonActionPerformed
        this.pelialusta.getNopat().get(4).saasta();        // TODO add your handling code here:
    }//GEN-LAST:event_noppa5ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(KayttoliittymaIkkuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(KayttoliittymaIkkuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(KayttoliittymaIkkuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(KayttoliittymaIkkuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new KayttoliittymaIkkuna().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Nopat;
    private javax.swing.JPanel Tulokset;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton heittoButton;
    private javax.swing.JLabel hyvitysLabel;
    private javax.swing.JButton isoSuoraButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton kakkosetButton;
    private javax.swing.JButton kaksiPariaButton;
    private javax.swing.JButton kolmesamaaButton;
    private javax.swing.JButton kolmosetButton;
    private javax.swing.JButton kutosetButton;
    private javax.swing.JButton neljasamaaButton;
    private javax.swing.JButton nelosetButton;
    private javax.swing.JButton noppa1Button;
    private javax.swing.JButton noppa2Button;
    private javax.swing.JButton noppa3Button;
    private javax.swing.JButton noppa4Button;
    private javax.swing.JButton noppa5Button;
    private javax.swing.JButton pariButton;
    private javax.swing.JLabel pelaajaLabel;
    private javax.swing.JButton sattumaButton;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel summaLabel;
    private javax.swing.JButton suoraButton;
    private javax.swing.JButton takariButton;
    private javax.swing.JLabel valisummaLabel;
    private javax.swing.JButton viitosetButton;
    private javax.swing.JButton yatsiButton;
    private javax.swing.JButton ykkosetButton;
    // End of variables declaration//GEN-END:variables
}
